version: '3.8'

services:
  go:
    build: .
    container_name: jwt-api
    ports:
      - "8000:8000"
    command: sh -c 'go mod tidy && air'
    working_dir: /api
    volumes:
      - ./:/api
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: books-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
